/**
 * images required throughout the app
 */
export const IMAGES = {
  noProducts: require('../assets/images/noproduct.png'),
  noOrders: require('../assets/images/noorder.png'),
  noCategories: require('../assets/images/nocategory.png'),
  noCustomers: require('../assets/images/nocustomer.png'),
  activeDashboard: require('../assets/images/dashboard_.png'),
  inActiveDashboard: require('../assets/images/dashboard.png'),
  activeProducts: require('../assets/images/products_.png'),
  inActiveProducts: require('../assets/images/products.png'),
  activeOrders: require('../assets/images/orders_.png'),
  inactiveOrders: require('../assets/images/orders.png'),
  activeCustomers: require('../assets/images/customers_.png'),
  inactiveCustomers: require('../assets/images/customers.png'),
  activeMore: require('../assets/images/more_.png'),
  inactiveMore: require('../assets/images/more.png'),
  arrowDown: require('../assets/images/down.png'),
  arrowUp: require('../assets/images/up.png'),
  arrowRightWhite: require('../assets/images/whitearrowright.png'),
  successImage: require('../assets/images/successimage.png'),
  arrowRight: require('../assets/images/arrowright.png'),
  arrowLeft: require('../assets/images/arrowleft.png'),
  makeMoney: require('../assets/images/makemoney.png'),
  storeSetup: require('../assets/images/storesetup.png'),
  urlError: require('../assets/images/urlerror.png'),
  urlGood: require('../assets/images/urlgood.png'),
  errorImage: require('../assets/images/error.png'),
  infoImage: require('../assets/images/info.png'),
  arrowRight_: require('../assets/images/arrow_right.png'),
  settingsImage: require('../assets/images/settings.png'),
  dispatchImage: require('../assets/images/dispatch.png'),
  storeDetailsImage: require('../assets/images/basicsettings.png'),
  storeShippingImage: require('../assets/images/shipping.png'),
  storePaymentImage: require('../assets/images/payment.png'),
  moreStoreOptionsImage: require('../assets/images/morestoreoptions.png'),
  editImage: require('../assets/images/edit.png'),
  addImage:require("../assets/images/add.png"),
  analyticsImage:require("../assets/images/analytics.png"),
  whatsappImage:require("../assets/images/whatsapp.png"),
  smsImage:require("../assets/images/sms.png"),

cancel : require('../assets/images/cancel.png')
};
